#!/bin/bash
python easy_train.py \
    --training-dataset=/workspace/nnue-pytorch/data/data_d9_2021_09_02.binpack \
    --validation-dataset=/workspace/nnue-pytorch/data/data_d9_2021_09_02.binpack \
    --num-workers=4 \
    --threads=2 \
    --gpus="0," \
    --runs-per-gpu=1 \
    --batch-size=16384 \
    --max_epoch=1 \
    --do-network-training=True \
    --do-network-testing=True \
    --tui=False \
    --network-save-period=1 \
    --random-fen-skipping=3 \
    --start-lambda=1.0 \
    --end-lambda=0.75 \
    --fail-on-experiment-exists=False \
    --build-engine-arch=x86-64-bmi2 \
    --build-threads=2 \
    --epoch-size=1638400 \
    --validation-size=16384 \
    --network-testing-threads=24 \
    --network-testing-explore-factor=1.5 \
    --network-testing-book=/workspace/scripts/easy_train_data_main/books/UHO_Lichess_4852_v1.epd \
    --network-testing-nodes-per-move=20000 \
    --network-testing-hash-mb=8 \
    --network-testing-games-per-round=200 \
    --engine-base-branch=official-stockfish/Stockfish/master \
    --engine-test-branch=official-stockfish/Stockfish/master \
    --nnue-pytorch-branch=vondele/nnue-pytorch/easy_train \
    --workspace-path=./easy_train_data \
    --experiment-name=test \
    --additional-training-arg="--auto_lr_find=False" \
    --additional-training-arg="--detect_anomaly=False" \
    --features="HalfKP" # 可能不支持HalfKAv2_hm^
